# Generated by Django 4.2.11 on 2024-05-30 10:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medic', '0003_customuser'),
    ]

    operations = [
        migrations.RenameField(
            model_name='socialauthdata',
            old_name='user_id',
            new_name='social_user_id',
        ),
        migrations.AddField(
            model_name='medic',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='medic', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='socialauthdata',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='medic',
            name='expertise',
            field=models.ManyToManyField(related_name='expertise', to='medic.expertise'),
        ),
        migrations.AlterField(
            model_name='medic',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location', to='medic.location'),
        ),
    ]
