# Generated by Django 4.2.11 on 2024-06-01 10:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medic', '0004_rename_user_id_socialauthdata_social_user_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('initiated', 'Initiated'), ('location_shared', 'Location Shared'), ('otp_sent', 'OTP Sent'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='initiated', max_length=20)),
                ('otp', models.CharField(blank=True, max_length=6, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('timeout_at', models.DateTimeField(blank=True, null=True)),
                ('medic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medic_bookings', to='medic.medic')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_bookings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
