# Generated by Django 4.2.11 on 2024-06-02 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medic', '0007_booking_extra_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='otp',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
